version: "2"
services:
 web:
    container_name: rentmate-cuenta-ms
    build: .
    image: rentmate-cuenta-ms
    ports:
    - "3000:3000"
    depends_on:
      - mongo
    networks:
      - shared
 mongo:
    container_name: rentmate-cuenta-db
    image: mongo  
    networks:
    - shared
    ports:
      - "27017:27017"
networks:
  shared:
    external: true